# Generated by Django 4.2.15 on 2024-08-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='weight',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
