# Generated by Django 5.1 on 2024-08-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
