# Generated by Django 4.2.15 on 2024-08-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_meal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='total_calories',
        ),
    ]
